### ISSUE TITLE
Choose Camera

### ISSUE THREAD

**Issue by IceT-max** [webermax/html5qrcodereader#1]
Hi, at the moment, most smartphone have more one camera.
An useful function must be choose the camera where capture the qrcode!
More useful must be, set in the javascript the preference, so no need to select the camera during the capture..

I hope to be clear!

**Comment by webermax** [comment]
hi,

thank you very much for your hint!

i am on it and we'll have this feature, soon.

**Comment by IceT-max** [comment]
Thanks a lot!
